### ISSUE TITLE
🐛 [BUG] Problem with nequip_calculator in ASE

### ISSUE THREAD

**Issue by tbraeckevelt** [mir-group/nequip#140]
When I try to run a MD NVT simulation with a deployed nequip model using ASE, a get the following error:

```
/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/nequip/scripts/deploy.py:115: UserWarning: Loaded model had a different value for _jit_bailout_depth than was currently set; changing the GLOBAL setting!
  warnings.warn(
Traceback (most recent call last):
  File "yaff_neq_MD.py", line 193, in <module>
    simulate(steps, step, start, atoms, calc_neq, temperature, pressure)
  File "yaff_neq_MD.py", line 144, in simulate
    verlet.run(steps)
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/yaff/sampling/iterative.py", line 128, in run
    if self.propagate():
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/yaff/sampling/verlet.py", line 351, in propagate
    self.epot = self.ff.compute(self.gpos, self.vtens)
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/yaff/pes/ff.py", line 157, in compute
    self.energy = self._internal_compute(my_gpos, my_vtens)
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/yaff/pes/ff.py", line 272, in _internal_compute
    result = sum([part.compute(gpos, vtens) for part in self.parts])
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/yaff/pes/ff.py", line 272, in <listcomp>
    result = sum([part.compute(gpos, vtens) for part in self.parts])
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/yaff/pes/ff.py", line 157, in compute
    self.energy = self._internal_compute(my_gpos, my_vtens)
  File "yaff_neq_MD.py", line 68, in _internal_compute
    energy = self.atoms.get_potential_energy() * molmod.units.electronvolt
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/ase/atoms.py", line 731, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/ase/calculators/abc.py", line 24, in get_potential_energy
    return self.get_property(name, atoms)
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/ase/calculators/calculator.py", line 499, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/nequip/ase/nequip_calculator.py", line 111, in calculate
    out = self.model(AtomicData.to_AtomicDataDict(data))
  File "/kyukon/scratch/gent/vo/000/gvo00003/vsc42365/ForInstall/YAFF_ASE_CP2K_NEQUIP/accelgor/yacn_acc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: default_program(18): error: expected a ")"

default_program(21): error: expected a ";"

default_program(23): error: expression must have class type

default_program(24): error: expression must have class type

default_program(25): error: expression must have class type

default_program(26): error: expression must have class type

default_program(28): error: expression must have class type

7 errors detected in the compilation of "default_program".

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_div_sin_div_mul_mul(float* t_, float* t__, float* aten_mul, float* aten_mul_1, float* aten_sin, float* aten_div, float* aten_mul_2, float* const_self.model.func.radial_basis.basis.bessel_weights) {
{
  if (512 * blockIdx.x + threadIdx.x<241728 ? 1 : 0) {
    float const_self.model.func.radial_basis.basis.bessel_weights_1 = __ldg(const_self.model.func.radial_basis.basis.bessel_weights + (512 * blockIdx.x + threadIdx.x) % 8);
    float t___1 = __ldg(t__ + (512 * blockIdx.x + threadIdx.x) / 8);
    aten_mul_2[512 * blockIdx.x + threadIdx.x] = const_self.model.func.radial_basis.basis.bessel_weights_1 * t___1;
    aten_div[512 * blockIdx.x + threadIdx.x] = (float)((double)(const_self.model.func.radial_basis.basis.bessel_weights_1 * t___1) / 6.0);
    aten_sin[512 * blockIdx.x + threadIdx.x] = sinf((float)((double)(const_self.model.func.radial_basis.basis.bessel_weights_1 * t___1) / 6.0));
    aten_mul_1[512 * blockIdx.x + threadIdx.x] = (float)((double)((sinf((float)((double)(const_self.model.func.radial_basis.basis.bessel_weights_1 * t___1) / 6.0))) / t___1) * 0.3333333333333333);
    float v = __ldg(t_ + (512 * blockIdx.x + threadIdx.x) / 8);
    aten_mul[512 * blockIdx.x + threadIdx.x] = (float)((double)((sinf((float)((double)(const_self.model.func.radial_basis.basis.bessel_weights_1 * t___1) / 6.0))) / t___1) * 0.3333333333333333) * v;
  }
}
}
```

I use the following code to create the nequip calculator:
```
from nequip.ase.nequip_calculator import NequIPCalculator
calc_neq = NequIPCalculator.from_deployed_model(model_path = path_model, 
                                                    species_to_type_name = {"C" : "C",
                                                                            "H" : "H",
                                                                            "N" : "N",
                                                                            "Pb": "Pb",
                                                                            "I" : "I" },
                                                    device='cuda')
```

I have installed nequip and other libraries with the following commands (I was using remote computing infrastructure for which Python 3.8.6 and CUDA 11.1.1 were already installed):
```
pip install numpy==1.19.5
pip install git+https://gitlab.com/ase/ase.git
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric==1.7.2 -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
pip install "git+https://github.com/Linux-cpp-lisp/pytorch_ema@context_manager#egg=torch_ema"
pip install git+https://github.com/mir-group/nequip 
pip install wandb
```

With this installation, I was able to successfully train a nequip model, the info of the trained model can be found in the following file:
[deployed_model_info.txt](https://github.com/mir-group/nequip/files/7907592/deployed_model_info.txt)

As I have no experience with Torch, I do not understand the underlying problem. For example. is this an installation problem, is there something wrong with the nequip model or am I defining the nequip calculator wrong? Could you maybe propose possible solutions or give any insight into this issue?

Kind regards
Tom

**Comment by Linux-cpp-lisp** [comment]
Hi @tbraeckevelt ,

Thanks for your interest in our code! 

This is a known issue upstream in PyTorch-- see discussion on [another NequIP issue here](https://github.com/mir-group/nequip/issues/121#issuecomment-989212636).

Long story short: upgrading to PyTorch 1.10 where the underlying issue is fixed should resolve this.

**Comment by Linux-cpp-lisp** [comment]
(Unrelated: I noticed in your config that you have set `allow_tf32: true`--- please note that we do not at this point recommend this as we have not yet fully understood the impact of reduced TF32 precision on the model or, in particular, its equivariance. If you have a reason to set this it should be fine, but if it somehow got set by accident you probably want it set to `False`.)

**Comment by Linux-cpp-lisp** [comment]
@tbraeckevelt great, glad to hear. And no worries this is a pretty odd error message to look up.

Closing this, feel free to open a new issue/discussion if you have other questions!
