### ISSUE TITLE
🐛 [BUG] Error when trying to use CUDA device with ASE calculator

### ISSUE THREAD

**Issue by mkphuthi** [mir-group/nequip#209]
**Describe the bug**
NequIP calculator fails with `device='cuda'` but works with `device='cpu'`

**To Reproduce**
```
at = Atoms(...)
calc = nequip.from_deployed_model('model.pth', device='cuda')
at.calc = calc
at.get_forces()
```

**Expected behavior**
Calculator works with either CUDA or CPU device

**Environment (please complete the following information):**
 - OS: CentOS
 - python version: 3.9
 - python environment (commands are given for python interpreter):
   - nequip 0.5.4
   - e3nn version 0.5.0
   - pytorch version 1.9.0+cu102
 - (if relevant) GPU support with CUDA
   -  cuda Version according to nvcc 10.2
   -  cuda version according to PyTorch 10.2

The stack trace is:
```
/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/nequip/scripts/deploy.py:109: UserWarning: Loaded model had a different value for allow_tf32 than was currently set; changing the GLOBAL setting!
  warnings.warn(
/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/nequip/scripts/deploy.py:120: UserWarning: Loaded model had a different value for _jit_bailout_depth than was currently set; changing the GLOBAL setting!
  warnings.warn(
Traceback (most recent call last):
  File "/home/mphuthi/Li/models/nequip/run1-6_v0_i0-1_low/nequip_test.py", line 12, in <module>
    ph = nq.phonon_bands_and_dos(
  File "/home/mphuthi/dev/calctest/calctest/calctest.py", line 812, in phonon_bands_and_dos
    ph.run()
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/ase/phonons.py", line 201, in run
    result = self.calculate(atoms_N, disp)
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/ase/phonons.py", line 320, in calculate
    forces = self(atoms_N)
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/ase/phonons.py", line 317, in __call__
    return atoms_N.get_forces()
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/ase/atoms.py", line 788, in get_forces
    forces = self._calc.get_forces(self)
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/ase/calculators/abc.py", line 23, in get_forces
    return self.get_property('forces', atoms)
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/nequip/ase/nequip_calculator.py", line 115, in calculate
    out = self.model(data)
  File "/home/mphuthi/.conda/envs/nequip-stress/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: default_program(18): error: expected a ")"

default_program(21): error: expected a ";"

default_program(23): error: expression must have class type

default_program(24): error: expression must have class type

default_program(25): error: expression must have class type

default_program(26): error: expression must have class type

default_program(28): error: expression must have class type

7 errors detected in the compilation of "default_program".

nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)


template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_div_sin_div_mul_mul(float* t_, float* t__, float* aten_mul, float* aten_mul_1, float* aten_sin, float* aten_div, float* aten_mul_2, float* const_self.model.energy_model.radial_basis.basis.bessel_weights) {
{
  if (512 * blockIdx.x + threadIdx.x<464000 ? 1 : 0) {
    float const_self.model.energy_model.radial_basis.basis.bessel_weights_1 = __ldg(const_self.model.energy_model.radial_basis.basis.bessel_weights + (512 * blockIdx.x + threadIdx.x) % 8);
    float t___1 = __ldg(t__ + (512 * blockIdx.x + threadIdx.x) / 8);
    aten_mul_2[512 * blockIdx.x + threadIdx.x] = const_self.model.energy_model.radial_basis.basis.bessel_weights_1 * t___1;
    aten_div[512 * blockIdx.x + threadIdx.x] = (float)((double)(const_self.model.energy_model.radial_basis.basis.bessel_weights_1 * t___1) / 6.0);
    aten_sin[512 * blockIdx.x + threadIdx.x] = sinf((float)((double)(const_self.model.energy_model.radial_basis.basis.bessel_weights_1 * t___1) / 6.0));
    aten_mul_1[512 * blockIdx.x + threadIdx.x] = (float)((double)((sinf((float)((double)(const_self.model.energy_model.radial_basis.basis.bessel_weights_1 * t___1) / 6.0))) / t___1) * 0.3333333333333333);
    float v = __ldg(t_ + (512 * blockIdx.x + threadIdx.x) / 8);
    aten_mul[512 * blockIdx.x + threadIdx.x] = (float)((double)((sinf((float)((double)(const_self.model.energy_model.radial_basis.basis.bessel_weights_1 * t___1) / 6.0))) / t___1) * 0.3333333333333333) * v;
  }
}
}
```

**Comment by Linux-cpp-lisp** [comment]
See https://github.com/mir-group/nequip/issues/140, this is a PyTorch version issue solved by updating to >=1.10.
