### ISSUE TITLE
Error with nequip-evaluate❓ [QUESTION]

### ISSUE THREAD

**Issue by txy159** [mir-group/nequip#448]
**Dear developers,**

**I tried to evaluate the trained model with the following command:**

nequip-evaluate --train-dir results/example --model results/best_model --batch-size 4 --output eval.xyz

**I got the following error message:**

Loading model...
loaded deployed model.
Loading original dataset...
Loaded dataset specified in config.yaml.
Using origial training dataset (7515 frames) minus training (6012 frames) and validation frames (753 frames), yielding a test set size of 750 frames.
Starting...
Traceback (most recent call last):
  File "/public/home/miniconda3/envs/allegro/bin/nequip-evaluate", line 8, in <module>
    sys.exit(main())
  File "/public/home/miniconda3/envs/allegro/lib/python3.8/site-packages/nequip/scripts/evaluate.py", line 372, in main
    out = model(AtomicData.to_AtomicDataDict(batch))
  File "/public/home/miniconda3/envs/allegro/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Unsupported value kind: Tensor

** The output file only contains 8 structures. Do you have any suggestions on solving this problem ?**

**Thanks in advance.**

**Comment by cw-tan** [comment]
Hi @txy159 ,

Thank you for your interest in `nequip`. We'll need quite a bit more information before we can give useful advice. 

1. Which version of `nequip` (and `allegro`) are you using? Have you incorporated any custom changes in the modules?
2. Is there more to the traceback? The error looks pretty terse - it's kinda hard to figure out what's wrong just from that.

**Comment by txy159** [comment]
Hi @cw-tan ,

Thanks for your reply. 

I fixed this problem by updating all the packages to their latest versions.

**Comment by cw-tan** [comment]
Great to hear @txy159!
